name: build_cbsl 

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'

jobs:
  build_cbsl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build

    - name: Run build_cbsl.py
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python workflows/build_cbsl.py 

    - name: Checkout repo branch data
      uses: actions/checkout@v2
      with:
        ref: 'data'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data, and push to repo branch data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        
        if [ "$(ls -A /tmp/tmp.lanka_data_timeseries 2>/dev/null)" ]; then
            cp -r /tmp/tmp.lanka_data_timeseries/* .
        fi
        echo "* $(date) build_cbsl" >> update.log
        

        git add .
        git commit -m "Build CBSL $(date)"
        git push origin data
